version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./pg-init-scripts/create-multiple-databases.sql:/docker-entrypoint-initdb.d/create-multiple-databases.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

  product-engine:
    build: product-engine/
    restart: no
    ports:
      - '9090:9090'
    links:
      - db

  origination:
    build: origination/
    restart: no
    ports:
      - '9094:9094'
    links:
      - payment-gate
      - product-engine
      - scoring
      - db

  api:
    build: api/
    restart: no
    ports:
      - '8083:8083'
    links:
      - origination

  scoring:
    build: scoring/
    restart: no
    ports:
      - '9095:9095'
    links:
      - product-engine

  payment-gate:
    build: payment-gate/
    restart: no
    ports:
      - '9096:9096'
    links:
      - product-engine

  merchant-provider:
    build: merchant-provider/
    restart: no
    ports:
      - '8080:8080'

volumes:
  db:
    driver: local