version: '3.8'
volumes:
  db:
    driver: local
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./pg-init-scripts/create-multiple-databases.sql:/docker-entrypoint-initdb.d/create-multiple-databases.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

  product-engine:
    build: product-engine/
    restart: no
    ports:
      - '9090:9090'
    links:
      - db

  origination:
    build: origination/
    restart: no
    ports:
      - '9094:9094'
    links:
      - payment-gate
      - product-engine
      - scoring
      - db

  api:
    build: api/
    restart: no
    ports:
      - '8083:8083'
    links:
      - origination

  scoring:
    build: scoring/
    restart: no
    ports:
      - '9095:9095'
    links:
      - product-engine

  payment-gate:
    build: payment-gate/
    restart: no
    ports:
      - '8081:8080'
      - '9096:9096'
    links:
      - product-engine

  merchant-provider:
    build: merchant-provider/
    restart: no
    ports:
      - '8080:8080'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,INTERNAL://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29093:29093
      - 9093:9093
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29093,INTERNAL://127.0.0.1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1