version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=fintech
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  product_engine:
    build: product-engine/
    restart: no
    ports:
      - '9090:9090'
    links:
      - db

volumes:
  db:
    driver: local