version: '3.8'
volumes:
  db:
    driver: local
services:

  db:
    image: huntress/postgres-partman:14
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./pg-init-scripts/create-multiple-databases.sql:/docker-entrypoint-initdb.d/create-multiple-databases.sql
      - ./pg-init-scripts/partman.sh:/docker-entrypoint-initdb.d/partman.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

  product-engine:
    build: product-engine/
    restart: no
    ports:
      - '9090:9090'
    links:
      - db

  origination:
    build: origination/
    restart: no
    ports:
      - '9094:9094'
    links:
      - payment-gate
      - product-engine
      - scoring
      - db

  api:
    build: api/
    restart: no
    ports:
      - '8083:8083'
    links:
      - origination

  scoring:
    build: scoring/
    restart: no
    ports:
      - '9095:9095'
    links:
      - product-engine

  payment-gate:
    build: payment-gate/
    restart: no
    ports:
      - '8081:8080'
      - '9096:9096'
    links:
      - product-engine

  merchant-provider:
    build: merchant-provider/
    restart: no
    ports:
      - '8080:8080'

  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181

  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1