global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: api
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['api:8080']

  - job_name: user-service
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['user-service:8080']
