server:
  port: 8083

api:
  client:
    origination:
      grpc:
        host: localhost
        port: 9094

user-service:
  host: http://localhost
  port: 8081
  api-key: user-service

jwt:
  token-secret: lsufnd4qsh34kfu82shdlfofpk28sh3shfpsi