server:
  port: 8080

api:
  client:
    origination:
      grpc:
        host: origination
        port: 9094

user-service:
  host: http://user-service
  port: 8080
  api-key: user-service

jwt:
  token-secret: lsufnd4qsh34kfu82shdlfofpk28sh3shfpsi

management:
  endpoint:
    health:
      enabled: true
      roles: ACTUATOR
      show-details: ALWAYS
      probes:
        enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
    caches:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - loggers
          - caches
  health:
    db:
      enabled: true
    diskspace:
      enabled: false
    group:
      readiness:
        include: '*'
      liveness:
        include: '*'