spring:
  liquibase:
    change-log: classpath:/db/changelog/db.change-log-master.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

  datasource:
    url: jdbc:postgresql://db:5432/user_service
    username: postgres
    password: postgres


jwt:
  token:
    secret: lsufnd4qsh34kfu82shdlfofpk28sh3shfpsi
    lifetime: 5m
  refresh:
    secret: kgosemgk8s43nf9v4nf7sjfjnsyd39djs84nd
    lifetime: 60m

auth-token: user-service

management:
  endpoint:
    health:
      enabled: true
      roles: ACTUATOR
      show-details: ALWAYS
      probes:
        enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
    caches:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - loggers
          - caches
  health:
    db:
      enabled: true
    diskspace:
      enabled: false
    group:
      readiness:
        include: '*'
      liveness:
        include: '*'