on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
<<<<<<< HEAD
          java-version: '18'
=======
          java-version: '17'
>>>>>>> template/master
          cache: 'gradle'
      - run: "./gradlew bootJar test --no-daemon --no-build-cache"

